### ISSUE TITLE
Cover would not get loaded

### ISSUE THREAD

**Issue by WebBuddha** [3OW/Medusa#1]
I've got some Cover (poster) which are not loaded.
The indexer is glotz.info, if I delete the series and create it new, with an other indexer, the Cover was shown and is loading succesfull.

I tried to do an image upadate via mass update and I'm recieving following error message inside the log.
I'm able to reproduce the error.
`2020-03-03 16:46:57 ERROR    Thread_0 :: [] Exception generated: invalid literal for int() with base 10: '680x1000'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 251, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/manage/handler.py", line 758, in massUpdate
    image_cache.replace_images(series_obj)
  File "/app/medusa/medusa/image_cache.py", line 167, in replace_images
    fill_cache(series_obj)
  File "/app/medusa/medusa/image_cache.py", line 339, in fill_cache
    _cache_image_from_indexer(series_obj, img_type)
  File "/app/medusa/medusa/image_cache.py", line 262, in _cache_image_from_indexer
    img_data = metadata_generator._retrieve_show_image(img_type_name, series_obj)
  File "/app/medusa/medusa/metadata/generic.py", line 773, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "/app/medusa/medusa/metadata/generic.py", line 908, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "/app/medusa/medusa/indexers/indexer_base.py", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/app/medusa/medusa/indexers/glotz/glotz_api.py", line 332, in _get_show_data
    self._parse_images(sid)
  File "/app/medusa/medusa/indexers/glotz/glotz_api.py", line 387, in _parse_images
    if isinstance(int(img.get('season')), int):
ValueError: invalid literal for int() with base 10: '680x1000'`

**Comment by 3OW** [comment]
> I've got some Cover (poster) which are not loaded.
> The indexer is glotz.info, if I delete the series and create it new, with an other indexer, the Cover was shown and is loading succesfull.
> 
> I tried to do an image upadate via mass update and I'm recieving following error message inside the log.
> I'm able to reproduce the error.
> `2020-03-03 16:46:57 ERROR Thread_0 :: [] Exception generated: invalid literal for int() with base 10: '680x1000' Traceback (most recent call last): File "/app/medusa/medusa/server/web/core/base.py", line 251, in async_call result = function(**kwargs) File "/app/medusa/medusa/server/web/manage/handler.py", line 758, in massUpdate image_cache.replace_images(series_obj) File "/app/medusa/medusa/image_cache.py", line 167, in replace_images fill_cache(series_obj) File "/app/medusa/medusa/image_cache.py", line 339, in fill_cache _cache_image_from_indexer(series_obj, img_type) File "/app/medusa/medusa/image_cache.py", line 262, in _cache_image_from_indexer img_data = metadata_generator._retrieve_show_image(img_type_name, series_obj) File "/app/medusa/medusa/metadata/generic.py", line 773, in _retrieve_show_image indexer_show_obj = self._get_show_data(show_obj) File "/app/medusa/medusa/metadata/generic.py", line 908, in _get_show_data my_show = self.indexer_api[int(series_id)] File "/app/medusa/medusa/indexers/indexer_base.py", line 399, in __getitem__ self._get_show_data(key, self.config['language']) File "/app/medusa/medusa/indexers/glotz/glotz_api.py", line 332, in _get_show_data self._parse_images(sid) File "/app/medusa/medusa/indexers/glotz/glotz_api.py", line 387, in _parse_images if isinstance(int(img.get('season')), int): ValueError: invalid literal for int() with base 10: '680x1000'`

This error should be fixed.
